export const ANZ_IMAGES = {
  prioritisation:
    "https://framerusercontent.com/images/G95ClMnz9Eofrduv1zLdsjJZWo.png",
  stakeholder:
    "https://framerusercontent.com/images/1saooxyRf3yeKwfcdtSqCcvP7sY.png",
  discoverySprint:
    "https://framerusercontent.com/images/Xj0TYYfQJEv6mi3pCVkY4YAqE.png",
  processOverview:
    "https://framerusercontent.com/images/ArWHhigHDfzgjzYx7OBAfAc2QJQ.png",
  baseline:
    "https://framerusercontent.com/images/EWxPkpzUGohwmwJwhiUzAo2svlM.png",
  monthlyWrap:
    "https://framerusercontent.com/images/hq2XwhtOmes3I2Pzm5RusBAZw.png",
  financialFitness:
    "https://framerusercontent.com/images/vP9GZKxZRbsxnp3kLdaueULo4.png",
  psychologyToolkit:
    "https://framerusercontent.com/images/sfJVuBAjptK0WlNFtDbtf1NgyQ.png",
  designPrinciples:
    "https://framerusercontent.com/images/DPYW3rgBoLCYadRXmR76gAUkcVE.png",
  contentFramework:
    "https://framerusercontent.com/images/q89fHhOBHojoCEQFwmcIKbKKbO8.png",
  featureHome:
    "https://framerusercontent.com/images/Uac134696sL61zUhCmeIzG0W8Y.png",
  monthlySnapshot:
    "https://framerusercontent.com/images/TNrGKSbrKWGwaDR9ATGtCgBUw0.png",
  financialForecast:
    "https://framerusercontent.com/images/2nvCzGJMHgA6BgFdoeelHveq6k.png",
  tipsChallenges:
    "https://framerusercontent.com/images/6DhA9vCXDdl3fXOZ96ZI75YZAg.png",
};
